services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=messanger

  valkey:
    image: valkey/valkey:9.0.3
    ports:
      - 6379:6379

  api:
    build:
      context: backend
    ports:
      - 3478:3478/udp
      #- 49152-65535:49152-65535/udp
      - 8080:8080
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/messanger
      - PUBLIC_IP=192.168.100.6
    depends_on:
      - postgres

  webrtc:
    build:
      context: webrtc
    #networks:
      #- host # dynamic port allocation is needed for TURN server and p2p webrtc
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/messanger
