services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=messanger

  valkey:
    image: valkey/valkey:9.0.3
    ports:
      - 6379:6379

  api:
    build:
      context: backend
    ports:
      - 3478:3478/udp
      #- 49152-65535:49152-65535/udp
      - 8080:8080
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/messanger?sslmode=disable
      - REDIS_URL=valkey:6379
      - VALKEY_URL=valkey:6379
      - PUBLIC_IP=192.168.100.6
      - VAPID_PUBLIC_KEY=BPTNpgj3cjWFNTiZH22QTdb600avvQAZ3PPhwNWILdT2q5zXdB3nLQ9Rd0QZ_sFU24gdxUEKNpbovVXbab2O0gY
      - VAPID_PRIVATE_KEY=TLI6GRxBORMCeVnjvGzzvqQuaMkty0r52bDRiImTJns
    depends_on:
      - postgres
      - valkey

  webrtc:
    build:
      context: webrtc_service
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/messanger?sslmode=disable
      - PUBLIC_IP=192.168.100.6
      - PORT=8081
