basePath: /
definitions:
  httperrors.ErrorResponse:
    properties:
      details:
        additionalProperties:
          type: string
        type: object
      error:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
  repository.Chat:
    properties:
      avatar_url:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: string
      metadata:
        items:
          type: integer
        type: array
      title:
        type: string
      type:
        $ref: '#/definitions/repository.ChatType'
      updated_at:
        type: string
    type: object
  repository.ChatType:
    enum:
    - private
    - group
    - channel
    type: string
    x-enum-varnames:
    - ChatTypePrivate
    - ChatTypeGroup
    - ChatTypeChannel
  repository.Message:
    properties:
      chat_id:
        type: string
      content:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: string
      reply_message_id:
        type: string
      sender_id:
        type: string
      topic_id:
        type: string
      updated_at:
        type: string
    type: object
  repository.Topic:
    properties:
      avatar_url:
        type: string
      chat_id:
        type: string
      creted_at:
        type: string
      deleted_at:
        type: string
      id:
        type: string
      title:
        type: string
      type:
        $ref: '#/definitions/repository.TopicType'
      updated_at:
        type: string
    type: object
  repository.TopicType:
    enum:
    - text_topic
    - voice_topic
    type: string
    x-enum-varnames:
    - TopicTypeTextTopic
    - TopicTypeVoiceTopic
  services.AccessToken:
    properties:
      token:
        type: string
    type: object
  services.CreateChatDTO:
    properties:
      title:
        example: General Chat
        type: string
      type:
        enum:
        - private
        - group
        - channel
        example: group
        type: string
    type: object
  services.CreateMessageDTO:
    properties:
      content:
        example: Hello, world!
        type: string
    type: object
  services.CreateTopicDTO:
    properties:
      title:
        example: General Chat
        type: string
      type:
        enum:
        - text_topic
        - voice_topic
        example: group
        type: string
    type: object
  services.LoginUserDTO:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  services.RegisterUserDTO:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API for a messenger application.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Messenger API
  version: "1.0"
paths:
  /chats/:
    get:
      consumes:
      - application/json
      description: Returns a list of all chats.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/repository.Chat'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: List all chats
      tags:
      - chats
    post:
      consumes:
      - application/json
      description: Create a new chat (private, group, or channel). The authenticated
        user becomes the owner.
      parameters:
      - description: Chat details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/services.CreateChatDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repository.Chat'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a chat
      tags:
      - chats
  /chats/{id}:
    get:
      consumes:
      - application/json
      description: Returns a chat by ID.
      parameters:
      - description: Chat ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repository.Chat'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get a chat by ID
      tags:
      - chats
  /chats/{id}/messages:
    get:
      consumes:
      - application/json
      description: Returns a list of all messages in a chat.
      parameters:
      - description: Chat ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/repository.Message'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: List all messages in a chat
      tags:
      - messages
    post:
      consumes:
      - application/json
      description: Creates a new message in a chat.
      parameters:
      - description: Chat ID
        in: path
        name: id
        required: true
        type: integer
      - description: Message details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/services.CreateMessageDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repository.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a new message in a chat
      tags:
      - messages
  /chats/{id}/topics:
    get:
      consumes:
      - application/json
      description: Returns a list of all topics in a chat.
      parameters:
      - description: Chat ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/repository.Topic'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: List all topics in a chat
      tags:
      - topics
    post:
      consumes:
      - application/json
      description: Creates a new topic in a chat.
      parameters:
      - description: Chat ID
        in: path
        name: id
        required: true
        type: integer
      - description: Topic details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/services.CreateTopicDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repository.Topic'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a new topic in a chat
      tags:
      - topics
  /topics/{id}/messages:
    get:
      consumes:
      - application/json
      description: Returns a list of all messages in a topic.
      parameters:
      - description: Topic ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/repository.Message'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: List all messages in a topic
      tags:
      - messages
    post:
      consumes:
      - application/json
      description: Creates a new message in a topic.
      parameters:
      - description: Topic ID
        in: path
        name: id
        required: true
        type: integer
      - description: Message details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/services.CreateMessageDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repository.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a new message in a topic
      tags:
      - messages
  /users/login:
    post:
      consumes:
      - application/json
      description: Log in a user.
      parameters:
      - description: User details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/services.LoginUserDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.AccessToken'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
      summary: Login a user
      tags:
      - users
  /users/register:
    post:
      consumes:
      - application/json
      description: Register a new user.
      parameters:
      - description: User details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/services.RegisterUserDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.AccessToken'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperrors.ErrorResponse'
      summary: Register a user
      tags:
      - users
securityDefinitions:
  BearerAuth:
    description: Type "Bearer " followed by your JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
