// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createUserCategory = `-- name: CreateUserCategory :one
INSERT INTO user_categories (user_id, name, chat_ids) VALUES ($1, $2, $3) RETURNING id, user_id, name, chat_ids, created_at, updated_at
`

type CreateUserCategoryParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Name    string    `json:"name"`
	ChatIds []byte    `json:"chat_ids"`
}

func (q *Queries) CreateUserCategory(ctx context.Context, arg *CreateUserCategoryParams) (*UserCategory, error) {
	row := q.db.QueryRow(ctx, createUserCategory, arg.UserID, arg.Name, arg.ChatIds)
	var i UserCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ChatIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteUserCategory = `-- name: DeleteUserCategory :exec
DELETE FROM user_categories WHERE id = $1 AND user_id = $2
`

type DeleteUserCategoryParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteUserCategory(ctx context.Context, arg *DeleteUserCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteUserCategory, arg.ID, arg.UserID)
	return err
}

const listUserCategories = `-- name: ListUserCategories :many
SELECT id, user_id, name, chat_ids, created_at, updated_at FROM user_categories WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListUserCategories(ctx context.Context, userID uuid.UUID) ([]*UserCategory, error) {
	rows, err := q.db.Query(ctx, listUserCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*UserCategory
	for rows.Next() {
		var i UserCategory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ChatIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserCategory = `-- name: UpdateUserCategory :one
UPDATE user_categories SET name = $2, chat_ids = $3, updated_at = NOW() WHERE id = $1 AND user_id = $4 RETURNING id, user_id, name, chat_ids, created_at, updated_at
`

type UpdateUserCategoryParams struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	ChatIds []byte    `json:"chat_ids"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateUserCategory(ctx context.Context, arg *UpdateUserCategoryParams) (*UserCategory, error) {
	row := q.db.QueryRow(ctx, updateUserCategory,
		arg.ID,
		arg.Name,
		arg.ChatIds,
		arg.UserID,
	)
	var i UserCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ChatIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
