// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addUserToChat = `-- name: AddUserToChat :exec
INSERT INTO chat_members (
    user_id,
    chat_id,
    role
) VALUES (
    $1, $2, $3
)
`

type AddUserToChatParams struct {
	UserID uuid.UUID `json:"user_id"`
	ChatID uuid.UUID `json:"chat_id"`
	Role   ChatRole  `json:"role"`
}

func (q *Queries) AddUserToChat(ctx context.Context, arg *AddUserToChatParams) error {
	_, err := q.db.Exec(ctx, addUserToChat, arg.UserID, arg.ChatID, arg.Role)
	return err
}

const checkPrivateChatExists = `-- name: CheckPrivateChatExists :one
SELECT chats.id FROM chats
JOIN chat_members cm1 ON cm1.chat_id = chats.id
JOIN chat_members cm2 ON cm2.chat_id = chats.id
WHERE chats.type = 'private'
  AND cm1.user_id = $1
  AND cm2.user_id = $2
LIMIT 1
`

type CheckPrivateChatExistsParams struct {
	UserID   uuid.UUID `json:"user_id"`
	UserID_2 uuid.UUID `json:"user_id_2"`
}

func (q *Queries) CheckPrivateChatExists(ctx context.Context, arg *CheckPrivateChatExistsParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, checkPrivateChatExists, arg.UserID, arg.UserID_2)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createChat = `-- name: CreateChat :one
INSERT INTO chats (
    title,
    type
) VALUES (
    $1, $2
) RETURNING id, title, type, avatar_url, metadata, created_at, updated_at, deleted_at
`

type CreateChatParams struct {
	Title string   `json:"title"`
	Type  ChatType `json:"type"`
}

func (q *Queries) CreateChat(ctx context.Context, arg *CreateChatParams) (*Chat, error) {
	row := q.db.QueryRow(ctx, createChat, arg.Title, arg.Type)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.AvatarUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getChat = `-- name: GetChat :one
SELECT id, title, type, avatar_url, metadata, created_at, updated_at, deleted_at FROM chats
WHERE id = $1
`

func (q *Queries) GetChat(ctx context.Context, id uuid.UUID) (*Chat, error) {
	row := q.db.QueryRow(ctx, getChat, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.AvatarUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const joinUserToChat = `-- name: JoinUserToChat :exec
INSERT INTO chat_members (
    user_id,
    chat_id
) VALUES (
    $1, $2
)
`

type JoinUserToChatParams struct {
	UserID uuid.UUID `json:"user_id"`
	ChatID uuid.UUID `json:"chat_id"`
}

func (q *Queries) JoinUserToChat(ctx context.Context, arg *JoinUserToChatParams) error {
	_, err := q.db.Exec(ctx, joinUserToChat, arg.UserID, arg.ChatID)
	return err
}

const listChatMembers = `-- name: ListChatMembers :many
SELECT users.id, users.username, users.password_hash, users.avatar_url, users.metadata, users.created_at, users.updated_at, users.deleted_at, users.last_seen_at from users
join chat_members on chat_members.user_id = users.id
where chat_members.chat_id = $1
`

func (q *Queries) ListChatMembers(ctx context.Context, chatID uuid.UUID) ([]*User, error) {
	rows, err := q.db.Query(ctx, listChatMembers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.AvatarUrl,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChats = `-- name: ListChats :many
SELECT chats.id, chats.title, chats.type, chats.avatar_url, chats.metadata, chats.created_at, chats.updated_at, chats.deleted_at from chats
left join chat_members on chat_members.chat_id = chats.id
where chat_members.user_id = $1
`

func (q *Queries) ListChats(ctx context.Context, userID uuid.UUID) ([]*Chat, error) {
	rows, err := q.db.Query(ctx, listChats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.AvatarUrl,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatsWithLastMessage = `-- name: ListChatsWithLastMessage :many
SELECT chats.id, chats.title, chats.type, chats.avatar_url, chats.metadata, chats.created_at, chats.updated_at, chats.deleted_at,
       m.id as m_id, m.chat_id as m_chat_id, m.topic_id as m_topic_id, m.sender_id as m_sender_id,
       m.reply_message_id as m_reply_message_id, m.content as m_content,
       m.created_at as m_created_at, m.updated_at as m_updated_at, m.deleted_at as m_deleted_at
FROM chats
LEFT JOIN chat_members ON chat_members.chat_id = chats.id
LEFT JOIN LATERAL (
    SELECT id, chat_id, topic_id, sender_id, reply_message_id, content, created_at, updated_at, deleted_at FROM messages
    WHERE messages.chat_id = chats.id AND messages.deleted_at IS NULL
    ORDER BY messages.created_at DESC
    LIMIT 1
) m ON true
WHERE chat_members.user_id = $1
`

type ListChatsWithLastMessageRow struct {
	ID              uuid.UUID  `json:"id"`
	Title           string     `json:"title"`
	Type            ChatType   `json:"type"`
	AvatarUrl       *string    `json:"avatar_url"`
	Metadata        []byte     `json:"metadata"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
	MID             uuid.UUID  `json:"m_id"`
	MChatID         uuid.UUID  `json:"m_chat_id"`
	MTopicID        *uuid.UUID `json:"m_topic_id"`
	MSenderID       uuid.UUID  `json:"m_sender_id"`
	MReplyMessageID *uuid.UUID `json:"m_reply_message_id"`
	MContent        *string    `json:"m_content"`
	MCreatedAt      time.Time  `json:"m_created_at"`
	MUpdatedAt      time.Time  `json:"m_updated_at"`
	MDeletedAt      *time.Time `json:"m_deleted_at"`
}

func (q *Queries) ListChatsWithLastMessage(ctx context.Context, userID uuid.UUID) ([]*ListChatsWithLastMessageRow, error) {
	rows, err := q.db.Query(ctx, listChatsWithLastMessage, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListChatsWithLastMessageRow
	for rows.Next() {
		var i ListChatsWithLastMessageRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.AvatarUrl,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MID,
			&i.MChatID,
			&i.MTopicID,
			&i.MSenderID,
			&i.MReplyMessageID,
			&i.MContent,
			&i.MCreatedAt,
			&i.MUpdatedAt,
			&i.MDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromChat = `-- name: RemoveUserFromChat :exec
DELETE FROM chat_members
WHERE user_id = $1 AND chat_id = $2
`

type RemoveUserFromChatParams struct {
	UserID uuid.UUID `json:"user_id"`
	ChatID uuid.UUID `json:"chat_id"`
}

func (q *Queries) RemoveUserFromChat(ctx context.Context, arg *RemoveUserFromChatParams) error {
	_, err := q.db.Exec(ctx, removeUserFromChat, arg.UserID, arg.ChatID)
	return err
}

const updateChat = `-- name: UpdateChat :one
UPDATE chats SET
    title = $2,
    metadata = $3,
    updated_at = NOW()
WHERE id = $1 RETURNING id, title, type, avatar_url, metadata, created_at, updated_at, deleted_at
`

type UpdateChatParams struct {
	ID       uuid.UUID `json:"id"`
	Title    string    `json:"title"`
	Metadata []byte    `json:"metadata"`
}

func (q *Queries) UpdateChat(ctx context.Context, arg *UpdateChatParams) (*Chat, error) {
	row := q.db.QueryRow(ctx, updateChat, arg.ID, arg.Title, arg.Metadata)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.AvatarUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const updateChatMuted = `-- name: UpdateChatMuted :one
UPDATE chats SET
    metadata = $2,
    updated_at = NOW()
WHERE id = $1 RETURNING id, title, type, avatar_url, metadata, created_at, updated_at, deleted_at
`

type UpdateChatMutedParams struct {
	ID       uuid.UUID `json:"id"`
	Metadata []byte    `json:"metadata"`
}

func (q *Queries) UpdateChatMuted(ctx context.Context, arg *UpdateChatMutedParams) (*Chat, error) {
	row := q.db.QueryRow(ctx, updateChatMuted, arg.ID, arg.Metadata)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.AvatarUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}
