// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const addUserToChat = `-- name: AddUserToChat :exec
INSERT INTO chat_members (
    user_id,
    chat_id,
    role
) VALUES (
    $1, $2, $3
)
`

type AddUserToChatParams struct {
	UserID uuid.UUID `json:"user_id"`
	ChatID uuid.UUID `json:"chat_id"`
	Role   ChatRole  `json:"role"`
}

func (q *Queries) AddUserToChat(ctx context.Context, arg *AddUserToChatParams) error {
	_, err := q.db.Exec(ctx, addUserToChat, arg.UserID, arg.ChatID, arg.Role)
	return err
}

const checkPrivateChatExists = `-- name: CheckPrivateChatExists :one
SELECT chats.id FROM chats
JOIN chat_members cm1 ON cm1.chat_id = chats.id
JOIN chat_members cm2 ON cm2.chat_id = chats.id
WHERE chats.type = 'private'
  AND cm1.user_id = $1
  AND cm2.user_id = $2
LIMIT 1
`

type CheckPrivateChatExistsParams struct {
	UserID   uuid.UUID `json:"user_id"`
	UserID_2 uuid.UUID `json:"user_id_2"`
}

func (q *Queries) CheckPrivateChatExists(ctx context.Context, arg *CheckPrivateChatExistsParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, checkPrivateChatExists, arg.UserID, arg.UserID_2)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createChat = `-- name: CreateChat :one
INSERT INTO chats (
    title,
    type
) VALUES (
    $1, $2
) RETURNING id, title, type, avatar_url, metadata, created_at, updated_at, deleted_at
`

type CreateChatParams struct {
	Title string   `json:"title"`
	Type  ChatType `json:"type"`
}

func (q *Queries) CreateChat(ctx context.Context, arg *CreateChatParams) (*Chat, error) {
	row := q.db.QueryRow(ctx, createChat, arg.Title, arg.Type)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.AvatarUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getChat = `-- name: GetChat :one
SELECT id, title, type, avatar_url, metadata, created_at, updated_at, deleted_at FROM chats
WHERE id = $1
`

func (q *Queries) GetChat(ctx context.Context, id uuid.UUID) (*Chat, error) {
	row := q.db.QueryRow(ctx, getChat, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.AvatarUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getChatLastMessage = `-- name: GetChatLastMessage :one
SELECT id, chat_id, topic_id, sender_id, reply_message_id, content, created_at, updated_at, deleted_at FROM messages
WHERE chat_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetChatLastMessage(ctx context.Context, chatID uuid.UUID) (*Message, error) {
	row := q.db.QueryRow(ctx, getChatLastMessage, chatID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.TopicID,
		&i.SenderID,
		&i.ReplyMessageID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const joinUserToChat = `-- name: JoinUserToChat :exec
INSERT INTO chat_members (
    user_id,
    chat_id
) VALUES (
    $1, $2
)
`

type JoinUserToChatParams struct {
	UserID uuid.UUID `json:"user_id"`
	ChatID uuid.UUID `json:"chat_id"`
}

func (q *Queries) JoinUserToChat(ctx context.Context, arg *JoinUserToChatParams) error {
	_, err := q.db.Exec(ctx, joinUserToChat, arg.UserID, arg.ChatID)
	return err
}

const listChatMembers = `-- name: ListChatMembers :many
SELECT users.id, users.username, users.password_hash, users.avatar_url, users.metadata, users.created_at, users.updated_at, users.deleted_at, users.last_seen_at from users
join chat_members on chat_members.user_id = users.id
where chat_members.chat_id = $1
`

func (q *Queries) ListChatMembers(ctx context.Context, chatID uuid.UUID) ([]*User, error) {
	rows, err := q.db.Query(ctx, listChatMembers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.AvatarUrl,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChats = `-- name: ListChats :many
SELECT chats.id, chats.title, chats.type, chats.avatar_url, chats.metadata, chats.created_at, chats.updated_at, chats.deleted_at from chats
left join chat_members on chat_members.chat_id = chats.id
where chat_members.user_id = $1
`

func (q *Queries) ListChats(ctx context.Context, userID uuid.UUID) ([]*Chat, error) {
	rows, err := q.db.Query(ctx, listChats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.AvatarUrl,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatsLastMessages = `-- name: ListChatsLastMessages :many
SELECT DISTINCT ON (messages.chat_id) id, chat_id, topic_id, sender_id, reply_message_id, content, created_at, updated_at, deleted_at FROM messages
WHERE messages.chat_id = ANY($1::uuid[])
  AND messages.deleted_at IS NULL
ORDER BY messages.chat_id, messages.created_at DESC
`

func (q *Queries) ListChatsLastMessages(ctx context.Context, dollar_1 []uuid.UUID) ([]*Message, error) {
	rows, err := q.db.Query(ctx, listChatsLastMessages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.TopicID,
			&i.SenderID,
			&i.ReplyMessageID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserChats = `-- name: ListUserChats :many
SELECT c.id, c.title, c.type, c.avatar_url, c.metadata, c.created_at, c.updated_at, c.deleted_at FROM chats c
JOIN chat_members cm ON cm.chat_id = c.id
WHERE cm.user_id = $1
ORDER BY c.updated_at DESC
`

func (q *Queries) ListUserChats(ctx context.Context, userID uuid.UUID) ([]*Chat, error) {
	rows, err := q.db.Query(ctx, listUserChats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.AvatarUrl,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromChat = `-- name: RemoveUserFromChat :exec
DELETE FROM chat_members
WHERE user_id = $1 AND chat_id = $2
`

type RemoveUserFromChatParams struct {
	UserID uuid.UUID `json:"user_id"`
	ChatID uuid.UUID `json:"chat_id"`
}

func (q *Queries) RemoveUserFromChat(ctx context.Context, arg *RemoveUserFromChatParams) error {
	_, err := q.db.Exec(ctx, removeUserFromChat, arg.UserID, arg.ChatID)
	return err
}

const updateChat = `-- name: UpdateChat :one
UPDATE chats SET
    title = $2,
    metadata = $3,
    updated_at = NOW()
WHERE id = $1 RETURNING id, title, type, avatar_url, metadata, created_at, updated_at, deleted_at
`

type UpdateChatParams struct {
	ID       uuid.UUID `json:"id"`
	Title    string    `json:"title"`
	Metadata []byte    `json:"metadata"`
}

func (q *Queries) UpdateChat(ctx context.Context, arg *UpdateChatParams) (*Chat, error) {
	row := q.db.QueryRow(ctx, updateChat, arg.ID, arg.Title, arg.Metadata)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.AvatarUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const updateChatAvatar = `-- name: UpdateChatAvatar :one
UPDATE chats SET
    avatar_url = $2,
    updated_at = NOW()
WHERE id = $1 RETURNING id, title, type, avatar_url, metadata, created_at, updated_at, deleted_at
`

type UpdateChatAvatarParams struct {
	ID        uuid.UUID `json:"id"`
	AvatarUrl *string   `json:"avatar_url"`
}

func (q *Queries) UpdateChatAvatar(ctx context.Context, arg *UpdateChatAvatarParams) (*Chat, error) {
	row := q.db.QueryRow(ctx, updateChatAvatar, arg.ID, arg.AvatarUrl)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.AvatarUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const updateChatMuted = `-- name: UpdateChatMuted :one
UPDATE chats SET
    metadata = $2,
    updated_at = NOW()
WHERE id = $1 RETURNING id, title, type, avatar_url, metadata, created_at, updated_at, deleted_at
`

type UpdateChatMutedParams struct {
	ID       uuid.UUID `json:"id"`
	Metadata []byte    `json:"metadata"`
}

func (q *Queries) UpdateChatMuted(ctx context.Context, arg *UpdateChatMutedParams) (*Chat, error) {
	row := q.db.QueryRow(ctx, updateChatMuted, arg.ID, arg.Metadata)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.AvatarUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const updateChatUpdatedAt = `-- name: UpdateChatUpdatedAt :exec
UPDATE chats SET updated_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateChatUpdatedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateChatUpdatedAt, id)
	return err
}
