// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitation.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createChatInvitation = `-- name: CreateChatInvitation :one
INSERT INTO invitation (
    user_id,
    chat_id
) VALUES (
    $1, $2
) RETURNING id
`

type CreateChatInvitationParams struct {
	UserID uuid.UUID `json:"user_id"`
	ChatID uuid.UUID `json:"chat_id"`
}

func (q *Queries) CreateChatInvitation(ctx context.Context, arg *CreateChatInvitationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createChatInvitation, arg.UserID, arg.ChatID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
