// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO messages (
    chat_id,
    sender_id,
    content
) VALUES (
    $1, $2, $3
) RETURNING id, chat_id, topic_id, sender_id, reply_message_id, content, created_at, updated_at, deleted_at
`

type CreateChatMessageParams struct {
	ChatID   uuid.UUID `json:"chat_id"`
	SenderID uuid.UUID `json:"sender_id"`
	Content  *string   `json:"content"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg *CreateChatMessageParams) (*Message, error) {
	row := q.db.QueryRow(ctx, createChatMessage, arg.ChatID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.TopicID,
		&i.SenderID,
		&i.ReplyMessageID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const createTopicMessage = `-- name: CreateTopicMessage :one
INSERT INTO messages (
    topic_id,
    sender_id,
    content,
    chat_id
) VALUES (
    $1, $2, $3, (select chat_id from topics where topics.id = $1)
) RETURNING id, chat_id, topic_id, sender_id, reply_message_id, content, created_at, updated_at, deleted_at
`

type CreateTopicMessageParams struct {
	TopicID  *uuid.UUID `json:"topic_id"`
	SenderID uuid.UUID  `json:"sender_id"`
	Content  *string    `json:"content"`
}

func (q *Queries) CreateTopicMessage(ctx context.Context, arg *CreateTopicMessageParams) (*Message, error) {
	row := q.db.QueryRow(ctx, createTopicMessage, arg.TopicID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.TopicID,
		&i.SenderID,
		&i.ReplyMessageID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT id, chat_id, topic_id, sender_id, reply_message_id, content, created_at, updated_at, deleted_at from messages
where chat_id = $1
`

func (q *Queries) ListChatMessages(ctx context.Context, chatID uuid.UUID) ([]*Message, error) {
	rows, err := q.db.Query(ctx, listChatMessages, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.TopicID,
			&i.SenderID,
			&i.ReplyMessageID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicMessages = `-- name: ListTopicMessages :many
SELECT id, chat_id, topic_id, sender_id, reply_message_id, content, created_at, updated_at, deleted_at from messages
where topic_id = $1
`

func (q *Queries) ListTopicMessages(ctx context.Context, topicID *uuid.UUID) ([]*Message, error) {
	rows, err := q.db.Query(ctx, listTopicMessages, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.TopicID,
			&i.SenderID,
			&i.ReplyMessageID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
