// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ChatRole string

const (
	ChatRoleOwner  ChatRole = "owner"
	ChatRoleAdmin  ChatRole = "admin"
	ChatRoleMember ChatRole = "member"
)

func (e *ChatRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatRole(s)
	case string:
		*e = ChatRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatRole: %T", src)
	}
	return nil
}

type NullChatRole struct {
	ChatRole ChatRole `json:"chat_role"`
	Valid    bool     `json:"valid"` // Valid is true if ChatRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatRole) Scan(value interface{}) error {
	if value == nil {
		ns.ChatRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatRole), nil
}

type ChatType string

const (
	ChatTypePrivate ChatType = "private"
	ChatTypeGroup   ChatType = "group"
	ChatTypeChannel ChatType = "channel"
)

func (e *ChatType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatType(s)
	case string:
		*e = ChatType(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatType: %T", src)
	}
	return nil
}

type NullChatType struct {
	ChatType ChatType `json:"chat_type"`
	Valid    bool     `json:"valid"` // Valid is true if ChatType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatType) Scan(value interface{}) error {
	if value == nil {
		ns.ChatType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatType), nil
}

type TopicType string

const (
	TopicTypeTextTopic  TopicType = "text_topic"
	TopicTypeVoiceTopic TopicType = "voice_topic"
)

func (e *TopicType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TopicType(s)
	case string:
		*e = TopicType(s)
	default:
		return fmt.Errorf("unsupported scan type for TopicType: %T", src)
	}
	return nil
}

type NullTopicType struct {
	TopicType TopicType `json:"topic_type"`
	Valid     bool      `json:"valid"` // Valid is true if TopicType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTopicType) Scan(value interface{}) error {
	if value == nil {
		ns.TopicType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TopicType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTopicType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TopicType), nil
}

type Chat struct {
	ID        uuid.UUID  `json:"id"`
	Title     string     `json:"title"`
	Type      ChatType   `json:"type"`
	AvatarUrl *string    `json:"avatar_url"`
	Metadata  []byte     `json:"metadata"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type ChatMember struct {
	ID       uuid.UUID  `json:"id"`
	UserID   uuid.UUID  `json:"user_id"`
	ChatID   uuid.UUID  `json:"chat_id"`
	Role     ChatRole   `json:"role"`
	JoinedAt time.Time  `json:"joined_at"`
	LeftAt   *time.Time `json:"left_at"`
}

type Message struct {
	ID             uuid.UUID  `json:"id"`
	ChatID         uuid.UUID  `json:"chat_id"`
	TopicID        *uuid.UUID `json:"topic_id"`
	SenderID       uuid.UUID  `json:"sender_id"`
	ReplyMessageID *uuid.UUID `json:"reply_message_id"`
	Content        *string    `json:"content"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	DeletedAt      *time.Time `json:"deleted_at"`
}

type PushSubscription struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	Endpoint string    `json:"endpoint"`
	P256dh   string    `json:"p256dh"`
	Auth     string    `json:"auth"`
}

type Topic struct {
	ID        uuid.UUID  `json:"id"`
	ChatID    uuid.UUID  `json:"chat_id"`
	Title     string     `json:"title"`
	AvatarUrl *string    `json:"avatar_url"`
	Type      TopicType  `json:"type"`
	CretedAt  time.Time  `json:"creted_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type User struct {
	ID           uuid.UUID  `json:"id"`
	Username     string     `json:"username"`
	PasswordHash string     `json:"password_hash"`
	AvatarUrl    *string    `json:"avatar_url"`
	Metadata     []byte     `json:"metadata"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
	LastSeenAt   time.Time  `json:"last_seen_at"`
}
