// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createWebPushSubscription = `-- name: CreateWebPushSubscription :exec
INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth)
VALUES ($1, $2, $3, $4)
`

type CreateWebPushSubscriptionParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Endpoint string    `json:"endpoint"`
	P256dh   string    `json:"p256dh"`
	Auth     string    `json:"auth"`
}

func (q *Queries) CreateWebPushSubscription(ctx context.Context, arg *CreateWebPushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, createWebPushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
	)
	return err
}

const getAllSubscriptions = `-- name: GetAllSubscriptions :many
SELECT id, user_id, endpoint, p256dh, auth FROM push_subscriptions
`

func (q *Queries) GetAllSubscriptions(ctx context.Context) ([]*PushSubscription, error) {
	rows, err := q.db.Query(ctx, getAllSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionByEndpoint = `-- name: GetSubscriptionByEndpoint :one
SELECT id, user_id, endpoint, p256dh, auth FROM push_subscriptions
WHERE endpoint = $1 LIMIT 1
`

func (q *Queries) GetSubscriptionByEndpoint(ctx context.Context, endpoint string) (*PushSubscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByEndpoint, endpoint)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
	)
	return &i, err
}

const getUserSubscriptions = `-- name: GetUserSubscriptions :many
SELECT id, user_id, endpoint, p256dh, auth FROM push_subscriptions
WHERE user_id = $1
`

func (q *Queries) GetUserSubscriptions(ctx context.Context, userID uuid.UUID) ([]*PushSubscription, error) {
	rows, err := q.db.Query(ctx, getUserSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebPushSubscription = `-- name: UpdateWebPushSubscription :exec
UPDATE push_subscriptions
SET user_id = $1, p256dh = $2, auth = $3
WHERE id = $4
`

type UpdateWebPushSubscriptionParams struct {
	UserID uuid.UUID `json:"user_id"`
	P256dh string    `json:"p256dh"`
	Auth   string    `json:"auth"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateWebPushSubscription(ctx context.Context, arg *UpdateWebPushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, updateWebPushSubscription,
		arg.UserID,
		arg.P256dh,
		arg.Auth,
		arg.ID,
	)
	return err
}
