// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscription.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createWebPushSubscription = `-- name: CreateWebPushSubscription :exec
INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth)
VALUES ($1, $2, $3, $4)
`

type CreateWebPushSubscriptionParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Endpoint string    `json:"endpoint"`
	P256dh   string    `json:"p256dh"`
	Auth     string    `json:"auth"`
}

func (q *Queries) CreateWebPushSubscription(ctx context.Context, arg *CreateWebPushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, createWebPushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
	)
	return err
}

const getAllSubscriptions = `-- name: GetAllSubscriptions :many
SELECT id, user_id, endpoint, p256dh, auth FROM push_subscriptions
`

func (q *Queries) GetAllSubscriptions(ctx context.Context) ([]*PushSubscription, error) {
	rows, err := q.db.Query(ctx, getAllSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
