// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: topic.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createChatTopic = `-- name: CreateChatTopic :one
INSERT INTO topics (
    chat_id,
    title,
    type
) VALUES (
    $1, $2, $3
) RETURNING id, chat_id, title, avatar_url, type, creted_at, updated_at, deleted_at
`

type CreateChatTopicParams struct {
	ChatID uuid.UUID `json:"chat_id"`
	Title  string    `json:"title"`
	Type   TopicType `json:"type"`
}

func (q *Queries) CreateChatTopic(ctx context.Context, arg *CreateChatTopicParams) (*Topic, error) {
	row := q.db.QueryRow(ctx, createChatTopic, arg.ChatID, arg.Title, arg.Type)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Title,
		&i.AvatarUrl,
		&i.Type,
		&i.CretedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getTopic = `-- name: GetTopic :one
SELECT id, chat_id, title, avatar_url, type, creted_at, updated_at, deleted_at from topics
where id = $1
`

func (q *Queries) GetTopic(ctx context.Context, id uuid.UUID) (*Topic, error) {
	row := q.db.QueryRow(ctx, getTopic, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Title,
		&i.AvatarUrl,
		&i.Type,
		&i.CretedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const listChatTopics = `-- name: ListChatTopics :many
SELECT id, chat_id, title, avatar_url, type, creted_at, updated_at, deleted_at from topics
where chat_id = $1
`

func (q *Queries) ListChatTopics(ctx context.Context, chatID uuid.UUID) ([]*Topic, error) {
	rows, err := q.db.Query(ctx, listChatTopics, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Title,
			&i.AvatarUrl,
			&i.Type,
			&i.CretedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
